// <auto-generated />
namespace AwakenYourSmile.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ClinicalHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClinicalHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201501072359185_ClinicalHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
