namespace AwakenYourSmile.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddingOdontogramItems : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Odontograms", "Item18A", c => c.String());
            AddColumn("dbo.Odontograms", "Item18B", c => c.String());
            AddColumn("dbo.Odontograms", "Item18C", c => c.String());
            AddColumn("dbo.Odontograms", "Item18D", c => c.String());
            AddColumn("dbo.Odontograms", "Item17A", c => c.String());
            AddColumn("dbo.Odontograms", "Item17B", c => c.String());
            AddColumn("dbo.Odontograms", "Item17C", c => c.String());
            AddColumn("dbo.Odontograms", "Item17D", c => c.String());
            AddColumn("dbo.Odontograms", "Item16A", c => c.String());
            AddColumn("dbo.Odontograms", "Item16B", c => c.String());
            AddColumn("dbo.Odontograms", "Item16C", c => c.String());
            AddColumn("dbo.Odontograms", "Item16D", c => c.String());
            AddColumn("dbo.Odontograms", "Item15A", c => c.String());
            AddColumn("dbo.Odontograms", "Item15B", c => c.String());
            AddColumn("dbo.Odontograms", "Item15C", c => c.String());
            AddColumn("dbo.Odontograms", "Item15D", c => c.String());
            AddColumn("dbo.Odontograms", "Item14A", c => c.String());
            AddColumn("dbo.Odontograms", "Item14B", c => c.String());
            AddColumn("dbo.Odontograms", "Item14C", c => c.String());
            AddColumn("dbo.Odontograms", "Item14D", c => c.String());
            AddColumn("dbo.Odontograms", "Item13A", c => c.String());
            AddColumn("dbo.Odontograms", "Item13B", c => c.String());
            AddColumn("dbo.Odontograms", "Item13C", c => c.String());
            AddColumn("dbo.Odontograms", "Item13D", c => c.String());
            AddColumn("dbo.Odontograms", "Item12A", c => c.String());
            AddColumn("dbo.Odontograms", "Item12B", c => c.String());
            AddColumn("dbo.Odontograms", "Item12C", c => c.String());
            AddColumn("dbo.Odontograms", "Item12D", c => c.String());
            AddColumn("dbo.Odontograms", "Item11A", c => c.String());
            AddColumn("dbo.Odontograms", "Item11B", c => c.String());
            AddColumn("dbo.Odontograms", "Item11C", c => c.String());
            AddColumn("dbo.Odontograms", "Item11D", c => c.String());
            AddColumn("dbo.Odontograms", "Item21A", c => c.String());
            AddColumn("dbo.Odontograms", "Item21B", c => c.String());
            AddColumn("dbo.Odontograms", "Item21C", c => c.String());
            AddColumn("dbo.Odontograms", "Item21D", c => c.String());
            AddColumn("dbo.Odontograms", "Item22A", c => c.String());
            AddColumn("dbo.Odontograms", "Item22B", c => c.String());
            AddColumn("dbo.Odontograms", "Item22C", c => c.String());
            AddColumn("dbo.Odontograms", "Item22D", c => c.String());
            AddColumn("dbo.Odontograms", "Item23A", c => c.String());
            AddColumn("dbo.Odontograms", "Item23B", c => c.String());
            AddColumn("dbo.Odontograms", "Item23C", c => c.String());
            AddColumn("dbo.Odontograms", "Item23D", c => c.String());
            AddColumn("dbo.Odontograms", "Item24A", c => c.String());
            AddColumn("dbo.Odontograms", "Item24B", c => c.String());
            AddColumn("dbo.Odontograms", "Item24C", c => c.String());
            AddColumn("dbo.Odontograms", "Item24D", c => c.String());
            AddColumn("dbo.Odontograms", "Item25A", c => c.String());
            AddColumn("dbo.Odontograms", "Item25B", c => c.String());
            AddColumn("dbo.Odontograms", "Item25C", c => c.String());
            AddColumn("dbo.Odontograms", "Item25D", c => c.String());
            AddColumn("dbo.Odontograms", "Item26A", c => c.String());
            AddColumn("dbo.Odontograms", "Item26B", c => c.String());
            AddColumn("dbo.Odontograms", "Item26C", c => c.String());
            AddColumn("dbo.Odontograms", "Item26D", c => c.String());
            AddColumn("dbo.Odontograms", "Item27A", c => c.String());
            AddColumn("dbo.Odontograms", "Item27B", c => c.String());
            AddColumn("dbo.Odontograms", "Item27C", c => c.String());
            AddColumn("dbo.Odontograms", "Item27D", c => c.String());
            AddColumn("dbo.Odontograms", "Item28A", c => c.String());
            AddColumn("dbo.Odontograms", "Item28B", c => c.String());
            AddColumn("dbo.Odontograms", "Item28C", c => c.String());
            AddColumn("dbo.Odontograms", "Item28D", c => c.String());
            AddColumn("dbo.Odontograms", "Item48A", c => c.String());
            AddColumn("dbo.Odontograms", "Item48B", c => c.String());
            AddColumn("dbo.Odontograms", "Item48C", c => c.String());
            AddColumn("dbo.Odontograms", "Item48D", c => c.String());
            AddColumn("dbo.Odontograms", "Item47A", c => c.String());
            AddColumn("dbo.Odontograms", "Item47B", c => c.String());
            AddColumn("dbo.Odontograms", "Item47C", c => c.String());
            AddColumn("dbo.Odontograms", "Item47D", c => c.String());
            AddColumn("dbo.Odontograms", "Item46A", c => c.String());
            AddColumn("dbo.Odontograms", "Item46B", c => c.String());
            AddColumn("dbo.Odontograms", "Item46C", c => c.String());
            AddColumn("dbo.Odontograms", "Item46D", c => c.String());
            AddColumn("dbo.Odontograms", "Item45A", c => c.String());
            AddColumn("dbo.Odontograms", "Item45B", c => c.String());
            AddColumn("dbo.Odontograms", "Item45C", c => c.String());
            AddColumn("dbo.Odontograms", "Item45D", c => c.String());
            AddColumn("dbo.Odontograms", "Item44A", c => c.String());
            AddColumn("dbo.Odontograms", "Item44B", c => c.String());
            AddColumn("dbo.Odontograms", "Item44C", c => c.String());
            AddColumn("dbo.Odontograms", "Item44D", c => c.String());
            AddColumn("dbo.Odontograms", "Item43A", c => c.String());
            AddColumn("dbo.Odontograms", "Item43B", c => c.String());
            AddColumn("dbo.Odontograms", "Item43C", c => c.String());
            AddColumn("dbo.Odontograms", "Item43D", c => c.String());
            AddColumn("dbo.Odontograms", "Item42A", c => c.String());
            AddColumn("dbo.Odontograms", "Item42B", c => c.String());
            AddColumn("dbo.Odontograms", "Item42C", c => c.String());
            AddColumn("dbo.Odontograms", "Item42D", c => c.String());
            AddColumn("dbo.Odontograms", "Item41A", c => c.String());
            AddColumn("dbo.Odontograms", "Item41B", c => c.String());
            AddColumn("dbo.Odontograms", "Item41C", c => c.String());
            AddColumn("dbo.Odontograms", "Item41D", c => c.String());
            AddColumn("dbo.Odontograms", "Item31A", c => c.String());
            AddColumn("dbo.Odontograms", "Item31B", c => c.String());
            AddColumn("dbo.Odontograms", "Item31C", c => c.String());
            AddColumn("dbo.Odontograms", "Item31D", c => c.String());
            AddColumn("dbo.Odontograms", "Item32A", c => c.String());
            AddColumn("dbo.Odontograms", "Item32B", c => c.String());
            AddColumn("dbo.Odontograms", "Item32C", c => c.String());
            AddColumn("dbo.Odontograms", "Item32D", c => c.String());
            AddColumn("dbo.Odontograms", "Item33A", c => c.String());
            AddColumn("dbo.Odontograms", "Item33B", c => c.String());
            AddColumn("dbo.Odontograms", "Item33C", c => c.String());
            AddColumn("dbo.Odontograms", "Item33D", c => c.String());
            AddColumn("dbo.Odontograms", "Item34A", c => c.String());
            AddColumn("dbo.Odontograms", "Item34B", c => c.String());
            AddColumn("dbo.Odontograms", "Item34C", c => c.String());
            AddColumn("dbo.Odontograms", "Item34D", c => c.String());
            AddColumn("dbo.Odontograms", "Item35A", c => c.String());
            AddColumn("dbo.Odontograms", "Item35B", c => c.String());
            AddColumn("dbo.Odontograms", "Item35C", c => c.String());
            AddColumn("dbo.Odontograms", "Item35D", c => c.String());
            AddColumn("dbo.Odontograms", "Item36A", c => c.String());
            AddColumn("dbo.Odontograms", "Item36B", c => c.String());
            AddColumn("dbo.Odontograms", "Item36C", c => c.String());
            AddColumn("dbo.Odontograms", "Item36D", c => c.String());
            AddColumn("dbo.Odontograms", "Item37A", c => c.String());
            AddColumn("dbo.Odontograms", "Item37B", c => c.String());
            AddColumn("dbo.Odontograms", "Item37C", c => c.String());
            AddColumn("dbo.Odontograms", "Item37D", c => c.String());
            AddColumn("dbo.Odontograms", "Item38A", c => c.String());
            AddColumn("dbo.Odontograms", "Item38B", c => c.String());
            AddColumn("dbo.Odontograms", "Item38C", c => c.String());
            AddColumn("dbo.Odontograms", "Item38D", c => c.String());
            AddColumn("dbo.Odontograms", "Item55A", c => c.String());
            AddColumn("dbo.Odontograms", "Item54A", c => c.String());
            AddColumn("dbo.Odontograms", "Item53A", c => c.String());
            AddColumn("dbo.Odontograms", "Item52A", c => c.String());
            AddColumn("dbo.Odontograms", "Item51A", c => c.String());
            AddColumn("dbo.Odontograms", "Item61A", c => c.String());
            AddColumn("dbo.Odontograms", "Item62A", c => c.String());
            AddColumn("dbo.Odontograms", "Item63A", c => c.String());
            AddColumn("dbo.Odontograms", "Item64A", c => c.String());
            AddColumn("dbo.Odontograms", "Item65A", c => c.String());
            AddColumn("dbo.Odontograms", "Item85A", c => c.String());
            AddColumn("dbo.Odontograms", "Item84A", c => c.String());
            AddColumn("dbo.Odontograms", "Item83A", c => c.String());
            AddColumn("dbo.Odontograms", "Item82A", c => c.String());
            AddColumn("dbo.Odontograms", "Item81A", c => c.String());
            AddColumn("dbo.Odontograms", "Item71A", c => c.String());
            AddColumn("dbo.Odontograms", "Item72A", c => c.String());
            AddColumn("dbo.Odontograms", "Item73A", c => c.String());
            AddColumn("dbo.Odontograms", "Item74A", c => c.String());
            AddColumn("dbo.Odontograms", "Item75A", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.Odontograms", "Item75A");
            DropColumn("dbo.Odontograms", "Item74A");
            DropColumn("dbo.Odontograms", "Item73A");
            DropColumn("dbo.Odontograms", "Item72A");
            DropColumn("dbo.Odontograms", "Item71A");
            DropColumn("dbo.Odontograms", "Item81A");
            DropColumn("dbo.Odontograms", "Item82A");
            DropColumn("dbo.Odontograms", "Item83A");
            DropColumn("dbo.Odontograms", "Item84A");
            DropColumn("dbo.Odontograms", "Item85A");
            DropColumn("dbo.Odontograms", "Item65A");
            DropColumn("dbo.Odontograms", "Item64A");
            DropColumn("dbo.Odontograms", "Item63A");
            DropColumn("dbo.Odontograms", "Item62A");
            DropColumn("dbo.Odontograms", "Item61A");
            DropColumn("dbo.Odontograms", "Item51A");
            DropColumn("dbo.Odontograms", "Item52A");
            DropColumn("dbo.Odontograms", "Item53A");
            DropColumn("dbo.Odontograms", "Item54A");
            DropColumn("dbo.Odontograms", "Item55A");
            DropColumn("dbo.Odontograms", "Item38D");
            DropColumn("dbo.Odontograms", "Item38C");
            DropColumn("dbo.Odontograms", "Item38B");
            DropColumn("dbo.Odontograms", "Item38A");
            DropColumn("dbo.Odontograms", "Item37D");
            DropColumn("dbo.Odontograms", "Item37C");
            DropColumn("dbo.Odontograms", "Item37B");
            DropColumn("dbo.Odontograms", "Item37A");
            DropColumn("dbo.Odontograms", "Item36D");
            DropColumn("dbo.Odontograms", "Item36C");
            DropColumn("dbo.Odontograms", "Item36B");
            DropColumn("dbo.Odontograms", "Item36A");
            DropColumn("dbo.Odontograms", "Item35D");
            DropColumn("dbo.Odontograms", "Item35C");
            DropColumn("dbo.Odontograms", "Item35B");
            DropColumn("dbo.Odontograms", "Item35A");
            DropColumn("dbo.Odontograms", "Item34D");
            DropColumn("dbo.Odontograms", "Item34C");
            DropColumn("dbo.Odontograms", "Item34B");
            DropColumn("dbo.Odontograms", "Item34A");
            DropColumn("dbo.Odontograms", "Item33D");
            DropColumn("dbo.Odontograms", "Item33C");
            DropColumn("dbo.Odontograms", "Item33B");
            DropColumn("dbo.Odontograms", "Item33A");
            DropColumn("dbo.Odontograms", "Item32D");
            DropColumn("dbo.Odontograms", "Item32C");
            DropColumn("dbo.Odontograms", "Item32B");
            DropColumn("dbo.Odontograms", "Item32A");
            DropColumn("dbo.Odontograms", "Item31D");
            DropColumn("dbo.Odontograms", "Item31C");
            DropColumn("dbo.Odontograms", "Item31B");
            DropColumn("dbo.Odontograms", "Item31A");
            DropColumn("dbo.Odontograms", "Item41D");
            DropColumn("dbo.Odontograms", "Item41C");
            DropColumn("dbo.Odontograms", "Item41B");
            DropColumn("dbo.Odontograms", "Item41A");
            DropColumn("dbo.Odontograms", "Item42D");
            DropColumn("dbo.Odontograms", "Item42C");
            DropColumn("dbo.Odontograms", "Item42B");
            DropColumn("dbo.Odontograms", "Item42A");
            DropColumn("dbo.Odontograms", "Item43D");
            DropColumn("dbo.Odontograms", "Item43C");
            DropColumn("dbo.Odontograms", "Item43B");
            DropColumn("dbo.Odontograms", "Item43A");
            DropColumn("dbo.Odontograms", "Item44D");
            DropColumn("dbo.Odontograms", "Item44C");
            DropColumn("dbo.Odontograms", "Item44B");
            DropColumn("dbo.Odontograms", "Item44A");
            DropColumn("dbo.Odontograms", "Item45D");
            DropColumn("dbo.Odontograms", "Item45C");
            DropColumn("dbo.Odontograms", "Item45B");
            DropColumn("dbo.Odontograms", "Item45A");
            DropColumn("dbo.Odontograms", "Item46D");
            DropColumn("dbo.Odontograms", "Item46C");
            DropColumn("dbo.Odontograms", "Item46B");
            DropColumn("dbo.Odontograms", "Item46A");
            DropColumn("dbo.Odontograms", "Item47D");
            DropColumn("dbo.Odontograms", "Item47C");
            DropColumn("dbo.Odontograms", "Item47B");
            DropColumn("dbo.Odontograms", "Item47A");
            DropColumn("dbo.Odontograms", "Item48D");
            DropColumn("dbo.Odontograms", "Item48C");
            DropColumn("dbo.Odontograms", "Item48B");
            DropColumn("dbo.Odontograms", "Item48A");
            DropColumn("dbo.Odontograms", "Item28D");
            DropColumn("dbo.Odontograms", "Item28C");
            DropColumn("dbo.Odontograms", "Item28B");
            DropColumn("dbo.Odontograms", "Item28A");
            DropColumn("dbo.Odontograms", "Item27D");
            DropColumn("dbo.Odontograms", "Item27C");
            DropColumn("dbo.Odontograms", "Item27B");
            DropColumn("dbo.Odontograms", "Item27A");
            DropColumn("dbo.Odontograms", "Item26D");
            DropColumn("dbo.Odontograms", "Item26C");
            DropColumn("dbo.Odontograms", "Item26B");
            DropColumn("dbo.Odontograms", "Item26A");
            DropColumn("dbo.Odontograms", "Item25D");
            DropColumn("dbo.Odontograms", "Item25C");
            DropColumn("dbo.Odontograms", "Item25B");
            DropColumn("dbo.Odontograms", "Item25A");
            DropColumn("dbo.Odontograms", "Item24D");
            DropColumn("dbo.Odontograms", "Item24C");
            DropColumn("dbo.Odontograms", "Item24B");
            DropColumn("dbo.Odontograms", "Item24A");
            DropColumn("dbo.Odontograms", "Item23D");
            DropColumn("dbo.Odontograms", "Item23C");
            DropColumn("dbo.Odontograms", "Item23B");
            DropColumn("dbo.Odontograms", "Item23A");
            DropColumn("dbo.Odontograms", "Item22D");
            DropColumn("dbo.Odontograms", "Item22C");
            DropColumn("dbo.Odontograms", "Item22B");
            DropColumn("dbo.Odontograms", "Item22A");
            DropColumn("dbo.Odontograms", "Item21D");
            DropColumn("dbo.Odontograms", "Item21C");
            DropColumn("dbo.Odontograms", "Item21B");
            DropColumn("dbo.Odontograms", "Item21A");
            DropColumn("dbo.Odontograms", "Item11D");
            DropColumn("dbo.Odontograms", "Item11C");
            DropColumn("dbo.Odontograms", "Item11B");
            DropColumn("dbo.Odontograms", "Item11A");
            DropColumn("dbo.Odontograms", "Item12D");
            DropColumn("dbo.Odontograms", "Item12C");
            DropColumn("dbo.Odontograms", "Item12B");
            DropColumn("dbo.Odontograms", "Item12A");
            DropColumn("dbo.Odontograms", "Item13D");
            DropColumn("dbo.Odontograms", "Item13C");
            DropColumn("dbo.Odontograms", "Item13B");
            DropColumn("dbo.Odontograms", "Item13A");
            DropColumn("dbo.Odontograms", "Item14D");
            DropColumn("dbo.Odontograms", "Item14C");
            DropColumn("dbo.Odontograms", "Item14B");
            DropColumn("dbo.Odontograms", "Item14A");
            DropColumn("dbo.Odontograms", "Item15D");
            DropColumn("dbo.Odontograms", "Item15C");
            DropColumn("dbo.Odontograms", "Item15B");
            DropColumn("dbo.Odontograms", "Item15A");
            DropColumn("dbo.Odontograms", "Item16D");
            DropColumn("dbo.Odontograms", "Item16C");
            DropColumn("dbo.Odontograms", "Item16B");
            DropColumn("dbo.Odontograms", "Item16A");
            DropColumn("dbo.Odontograms", "Item17D");
            DropColumn("dbo.Odontograms", "Item17C");
            DropColumn("dbo.Odontograms", "Item17B");
            DropColumn("dbo.Odontograms", "Item17A");
            DropColumn("dbo.Odontograms", "Item18D");
            DropColumn("dbo.Odontograms", "Item18C");
            DropColumn("dbo.Odontograms", "Item18B");
            DropColumn("dbo.Odontograms", "Item18A");
        }
    }
}
